[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tic_tac_toe = "AmjKDcAmfZHesXUmcn3e8Z1jDoDActvSm9ooZXiUKuTY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
